### ISSUE TITLE
Collegare a smartphome ?

### ISSUE THREAD

**Issue by gaionim** [demarchidaniele/uWSPRBeacon#1]
Ciao,
cercavo un progetto per un beacon wspr portatile e sono capitato sul tuo.
Sono all'inizio della ricerca, quindi "porta pazienza" se scrivo obbrobri.

Mi domandavo se hai valutato la possibilità di usare gps e schermo di uno smartphone, da collegare via bluetooth ( e nel caso, perchè la hai scartata )
Dovrebbe semplificare la gestione dell'interfaccia ed evitare i relativi moduli.  
Se serve una mano potrei riprendere  https://github.com/kivy/python-for-android per un'interfaccia minimale.

73 da IU2HDS

**Comment by demarchidaniele** [comment]
Ciao Mauro,
     l'utilizzo di un telefono per leggere il GPS e/o controllare le impostazioni dell'arduino utilizzato nel mio beacon WPRS snaturerebbe il progetto stesso.
Questo progetto nasce per essere un Beacon stand-alone, controllabile via WEB, ed il più economico possibile.
Funziona anche senza modulo GPS attraverso la regolazione dell'orologio via internet, ed il display  è opzionale.
L'accoppiata ad un telefono aumenterebbe di molto il costo del tutto nonché, per alcuni, anche la costruzione e la programmazione (bisogna mettere mano al software su due dispositivi).

Se vuoi cimentarti nella sperimentazione puoi prendere i sorgenti che ho pubblicato e modificarli a tuo piacimento.

Buon 2018!
73 de IU3AGC - Daniele
